### ISSUE TITLE
UnicodeError // JSON

### ISSUE THREAD

**Issue by deviharisakthi** [sushant10/HQ_Bot#10]
C:\Users\Hari\HQ_Bot>python answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 263, in <module>
    load_json()
  File "answer_bot.py", line 53, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\Hari\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to undefined

**Comment by PoonamChohdhary1991** [comment]
ME TOO
$ py answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 263, in <module>
    load_json()
  File "answer_bot.py", line 53, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\Gandalf\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>

**Comment by sushant10** [comment]
You need to use python3 not python.

**Comment by LearntoDesign99** [comment]
I have the same issue and I am using python3 on windows.  I have a slight fix by adding ", encoding='ansi'" to the load_json function.  However now when it loads, the words are all jumbled and the characters do not show correctly.

**Comment by sushant10** [comment]
I'm not sure but the encoding might be utf8. Also i dont think that is the problem.

**Comment by Wacklebee** [comment]
Anyone have a fix for this? I just get unexpected keyword arguement when I add in encoding="ansi"
