### ISSUE TITLE
Error on typing "s"

### ISSUE THREAD

**Issue by Llama1412** [sushant10/HQ_Bot#115]
```
PS C:\Users\Dominic\Desktop\HQ_Bot-master> python .\answer_bot.py

Press s to screenshot live game, sampq to run against sample questions or q to quit:
s
| Reading screenTraceback (most recent call last):
  File ".\answer_bot.py", line 288, in <module>
    get_points_live()
  File ".\answer_bot.py", line 266, in get_points_live
    question,options=parse_question()
  File ".\answer_bot.py", line 119, in parse_question
    text = read_screen()
  File ".\answer_bot.py", line 100, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\Dominic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\Dominic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Dominic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\Dominic\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Dominic\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Can anyone help me with this?

**Comment by ilovecats516** [comment]
I have the same problem.

**Comment by stiefin90** [comment]
SO DO I

**Comment by ilovecats516** [comment]
Enetr this into your terminal: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then enter `brew install tesseract`

**Comment by SN4KE412** [comment]
Anyone found a way to fix this error yet?
