### ISSUE TITLE
Unknow Erreur

### ISSUE THREAD

**Issue by exhelios** [sushant10/HQ_Bot#118]
here what I get : 
⡿ Googling and searching WikipediaError accessing: http://www.google.com/search?nl=en&q=++wiki&start=0&num=10
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
Traceback (most recent call last):
  File "answer_bot.py", line 288, in <module>
    get_points_live()
  File "answer_bot.py", line 274, in get_points_live
⣟ Googling and searching Wikipedia    points,maxo = google_wiki(simq, options, neg)
  File "answer_bot.py", line 223, in google_wiki
    link = search_wiki[0].link
IndexError: list index out of range

Someone no how to resolve this ?

**Comment by egi2302** [comment]
Try this

cd /Applications/Python\ 3.6/
./Install\ Certificates.command
