### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by Waderaid** [sushant10/HQ_Bot#13]
HI i am using Windows and php and getting this error
C:\Users\wader\HQ_Bot>pip3 install -r requirements.txt
Requirement already satisfied: simplejson in c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Collecting Google-Search-API (from -r requirements.txt (line 2))
  Using cached Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extern\__init__.py:1: UserWarning: Module google was already imported from None, but c:\users\wader\appdata\local\temp\pip-build-3dx_4ub1\google-search-api is being added to sys.path
      from pkg_resources.extern import VendorImporter
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, map
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3147, in <module>
        @_call_aside
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3131, in _call_aside
        f(*args, **kwargs)
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3175, in _initialize_master_working_set
        for dist in working_set
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3175, in <genexpr>
        for dist in working_set
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2701, in activate
        declare_namespace(pkg)
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2260, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\wader\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2195, in _handle_ns
        loader.load_module(packageName)
      File ".\google\__init__.py", line 1, in <module>
        from modules import calculator, currency, images, utils
    ModuleNotFoundError: No module named 'modules'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\wader\AppData\Local\Temp\pip-build-3dx_4ub1\Google-Search-API\

**Comment by deviharisakthi** [comment]
Install using `pip install git+https://github.com/abenassi/Google-Search-API/` This worked for me.

**Comment by sushant10** [comment]
@deviharisakthi is correct.
