### ISSUE TITLE
Problem I am facing while launching the bot sometimes and the sample questions

### ISSUE THREAD

**Issue by MJ4LIFE2001** [sushant10/HQ_Bot#133]
When I am trying to test the bot using the sampq command, I get the following error message:
 Googling and searching WikipediaError accessing: http://www.google.com/search?nl=en&q=minky+mantel+wiki&start=0&num=10
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
Traceback (most recent call last):
  File "answer_bot.py", line 290, in <module>
    get_points_sample()
  File "answer_bot.py", line 255, in get_points_sample
    points, maxo = google_wiki(simq, options,neg)
  File "answer_bot.py", line 223, in google_wiki
    link = search_wiki[0].link
IndexError: list index out of range

Could someone please explain how to fix this issue?

**Comment by sixthhokage4** [comment]
I am facing the same problem. Please help!
