### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by gtaayush11** [sushant10/HQ_Bot#137]
Traceback (most recent call last):[0m[0m[0m
[0m[0m[0m  File "C:\Users\gtaso\AppData\Local\Programs\Python\Python36\HQ_Bot\answer_bot.py", line 281, in <module>
    load_json()
[0m[0m[0m[0m[0m[0m  File "C:\Users\gtaso\AppData\Local\Programs\Python\Python36\HQ_Bot\answer_bot.py", line 61, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
[0m[0m[0m[0m[0m[0m  File "C:\Users\gtaso\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
[0m[0m[0m[0m[0m[0mUnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>
[0m[0m[0m[0m[0m[0m
>>>

**Comment by thaysen13** [comment]
Getting same error
