### ISSUE TITLE
decoding Error while loading up the answer_bot.py

### ISSUE THREAD

**Issue by kishorek437** [sushant10/HQ_Bot#151]
im pretty new to python...and all this
so how to fix this??? im getting this error..
ive already googled the error and didnt find any working solution

C:\Users\CIE\Desktop\BOT BUILD\HQ_Bot-master>python3 answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 284, in <module>
    load_json()
  File "answer_bot.py", line 64, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\CIE\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 93: character maps to <undefined>

**Comment by kishorek437** [comment]
Got the fix on previous issues.. thanks
