### ISSUE TITLE
Tesseract error

### ISSUE THREAD

**Issue by kvmsc** [sushant10/HQ_Bot#19]
I don't understand this error.
`sherlock@sherlock` ~/Documents/HQ_Bot-master $ python3 answer_bot.py

Press s to screenshot live game, sampq to run against sample questions or q to quit:
s
Traceback (most recent call last):
  File "answer_bot.py", line 271, in <module>
    get_points_live()
  File "answer_bot.py", line 249, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 106, in parse_question
    text = read_screen()
  File "answer_bot.py", line 88, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 116, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file /usr/local/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.'`

**Comment by sushant10** [comment]
make sure you have tesseract installed properly

**Comment by kvmsc** [comment]
The TESSDATA_PREFIX was not set. All set!
Any others who faced the same error use this.
# export TESSDATA_PREFIX = /usr/share/tesseract-ocr

**Comment by yapal** [comment]
how to make it? TESSDATA_PREFIX= /usr/share/tesseract-ocr

**Comment by kvmsc** [comment]
Paste the following export command in the bash.
export TESSDATA_PREFIX=/usr/share/tesseract-ocr

**Comment by yapal** [comment]
how to know my path (yours i= /usr/share/tesseract-ocr)

**Comment by kvmsc** [comment]
No it automatically detects your directory. Try the same command and post the result.

**Comment by yapal** [comment]
before that this error bro:
Traceback (most recent call last):
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 280, in <module>
    get_points_live()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 258, in get_points_live
    question,options=parse_question()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 115, in parse_question
    text = read_screen()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 97, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>

**Comment by kvmsc** [comment]
It seems that you haven't installed tesseract. Try installing again. This article helped me. https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32

**Comment by yapal** [comment]
Should I export TESSDATA_PREFIX in cmd going to tesseract directory?
