### ISSUE TITLE
google.search('query',num) returns empty set

### ISSUE THREAD

**Issue by kvmsc** [sushant10/HQ_Bot#22]
Please help.

Traceback (most recent call last):
  File "answer_bot.py", line 277, in <module>
    get_points_live()
  File "answer_bot.py", line 263, in get_points_live
    points,maxo = google_wiki(simq, options, neg)
  File "answer_bot.py", line 211, in google_wiki
    link = search_wiki[0].link
IndexError: list index out of range

**Comment by sushant10** [comment]
Is it for live game?

**Comment by kvmsc** [comment]
No. I've taken screenshots from live games and have been trying this script.
