### ISSUE TITLE
Charmap issues now 

### ISSUE THREAD

**Issue by enegronjr** [sushant10/HQ_Bot#27]
Traceback (most recent call last):
  File "reader.py", line 262, in <module>
    load_json()
  File "reader.py", line 49, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>

**Comment by tombets2424** [comment]
Any ideas??? thanks.

python answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 276, in <module>
    load_json()
  File "answer_bot.py", line 63, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>

**Comment by enegronjr** [comment]
I fixed this error and forgot to close, I will look at my computer later tonight and find out what I did

**Comment by tombets2424** [comment]
Ok thank you.

**Comment by enegronjr** [comment]
closing this since there's another thread
