### ISSUE TITLE
charmap error!

### ISSUE THREAD

**Issue by tombets2424** [sushant10/HQ_Bot#30]
any help resolving this appreciated...

 python answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 276, in <module>
    load_json()
  File "answer_bot.py", line 63, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>

**Comment by enegronjr** [comment]
So I'm not sure which of these work, or if they worked together.
1. In the answer_bot.py, I added a line at the very beginning "file = open("answer_bot.py", encoding="Latin-1")". I read somewhere that the language that it was encoding in could be wrong and to set it at the beginning of the program.
2. I opened cp1252.py and commented out the line containing 0x9d, since it was undefined. 
If you have any questions, feel free to keep them coming!

**Comment by enegronjr** [comment]
Any luck?

**Comment by tombets2424** [comment]
hello, yes! the second one worked (to get rid of that line). sorry it took me awhile, we're from different time zones.

**Comment by tombets2424** [comment]
got a different error after fixing that one?
![image](https://user-images.githubusercontent.com/36307300/37357981-b9715be6-26e1-11e8-824f-18f1dd06dc5b.png)

thanks for help.

**Comment by enegronjr** [comment]
I had the same issue, I believe I just added "shell=True" into the parentheses on line 111 of pytesseract.py

**Comment by tombets2424** [comment]
okay, did that (I believe correctly as I got a new error). The code is just below the grey bar.
![image](https://user-images.githubusercontent.com/36307300/37364728-3c37c6ee-26f3-11e8-9d06-9e1f76691aa5.png)

This is the actual error...
![image](https://user-images.githubusercontent.com/36307300/37364771-58bd32cc-26f3-11e8-954f-e4f754f8f9b3.png)

Hopefully you got that error to and fixed it? xD

**Comment by enegronjr** [comment]
I had to edit my environmental variables. edit the variable path, then add "C:\Program Files (86x)\Tesseract-OCR\tesseract.exe"

**Comment by tombets2424** [comment]
yeah I have no idea where to put that exactly :?

**Comment by enegronjr** [comment]
type in your search bar "evnironmental varibles" and select the first thing that pops up. Then select Environment Variables on the bottom of the window. In the bottom half of the next window, find the varible path in the left column. Select it then click edit. In the next window click add then copy and paste 
"C:\Program Files (86x)\Tesseract-OCR\tesseract.exe" into the new text box. 

I would attach pictures but I am currently using a school computer and I don't have access to it.

**Comment by tombets2424** [comment]
I somehow don't have 'environmental variables' folders or files anywhere. only three environment python files. I must have done something wrong somewhere else, unless I'm just stupid!!

**Comment by enegronjr** [comment]
It's not a folder, its a setting on the computer

**Comment by tombets2424** [comment]
ahhh I am stupid. I don't have tesseract installed in that location? like tesseract isn't even located in Program Files (86x) at all. Do I need it installed there?

**Comment by enegronjr** [comment]
No just find where it's located and paste that

**Comment by tombets2424** [comment]
ahhhh... I'm giving up for today but, thanks! I feel like I'm getting closer but then another error occurs. Have you used this yet or do you have errors?

**Comment by enegronjr** [comment]
I still have an error on mine. I've had so many and you're running into the
same ones I am and luckily I still remember what I did

**Comment by yapal** [comment]
after adding shell=True, im getting this error. i also added path variable. this is error im getting:
uit:
[0ms
Traceback (most recent call last):
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 280, in <module>
    get_points_live()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 258, in get_points_live
    question,options=parse_question()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 115, in parse_question
    text = read_screen()
  File "C:\Python36\Scripts\HQ_Bot\answer_bot.py", line 97, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python36\lib\site-packages\pytesseract\pytesseract.py", line 116, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, "'tesseract' is not recognized as an internal or external command, operable program or batch file.")

**Comment by yapal** [comment]
this is what i have in path :
C:\Python36\Scripts\;C:\Python36\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd\;C:\Program Files\Tesseract-OCR\tesseract\;

**Comment by 0bytedna** [comment]
i have the same issue.

**Comment by 0bytedna** [comment]
@sushant10 bro, can you help fixing this error?

**Comment by enegronjr** [comment]
@0bytedna if you give me more info on your case I'll help

**Comment by 0bytedna** [comment]
I commented out the line containing 0x9d, works fine now. But throws a new error. I just opened a new thread with that error.

**Comment by 0bytedna** [comment]
All good now, commented out the line containing 0x9d, and added shell=True in line 111. But, the script runs very slowly.

**Comment by Jimmychou2** [comment]
how do i fix this?

![image](https://user-images.githubusercontent.com/37646631/37749579-f4784532-2d5e-11e8-90c0-cc369efd5f24.png)

**Comment by 0bytedna** [comment]
Probably tesseract or PIL package issue

**Comment by IanNS333** [comment]
Now I am having this error.

![image](https://user-images.githubusercontent.com/17051143/38179769-8614953c-35ec-11e8-99ec-287b1f9ee2d9.png)

**Comment by nanip9997** [comment]
@IanNS333 did you add the tessdata to your environment variables hope it works you need to add it to make the tesseract fully functional
