### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by 0bytedna** [sushant10/HQ_Bot#37]
![screenshot 27](https://user-images.githubusercontent.com/7030200/37619735-59ef21a4-2be0-11e8-95f1-0c7a53709aa5.png)

D:\WorkStation\Test Zone\HQ_Bot-master>python answer_bot.py
[93m
Press s to screenshot live game, sampq to run against sample questions or q to quit:
[0ms
Traceback (most recent call last):
  File "answer_bot.py", line 281, in <module>
    get_points_live()
  File "answer_bot.py", line 259, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 116, in parse_question
    text = read_screen()
  File "answer_bot.py", line 98, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\ZeroByteDNA\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\ZeroByteDNA\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\ZeroByteDNA\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\ZeroByteDNA\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\ZeroByteDNA\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Shankdizzl3** [comment]
What did you find to be the problem?

**Comment by jainyankee1993** [comment]
YES HELP. What was the problem?? Any solution??

**Comment by stiefin90** [comment]
help please i have the same problem
