### ISSUE TITLE
pls helpe with unicode error

### ISSUE THREAD

**Issue by julian2355** [sushant10/HQ_Bot#38]
C:\Users\julia\Desktop\hqbot>python answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 282, in <module>
    load_json()
  File "answer_bot.py", line 64, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 93: character maps to <undefined>

**Comment by 0bytedna** [comment]
Don't open duplicate issues. There is already a thread named charmap error open. Close this thread.

**Comment by julian2355** [comment]
ive seen it and there is no fix for my issue

**Comment by yapal** [comment]
Go to C:\Python36-32\lib\encodings\cp1252.py ,, edit with idle and go to line 111 and uncomment line. Save and run bot again

**Comment by 0bytedna** [comment]
@julian2355 if you read the thread properly, you will find the fix.

**Comment by yapal** [comment]
Sorry in my previous comment I I said to delete line 111 ( got confused with other issue). Go to same cp1252.py and find 0x9d by using find And delete it then save and run again. And if u followed my previous comment uninstall modules and reinstall. But u may get errors if u had deleted line 111
