### ISSUE TITLE
Unknown error when running

### ISSUE THREAD

**Issue by ItsCresent** [sushant10/HQ_Bot#41]
```
Traceback (most recent call last):[0m[0m[0m
[0m[0m[0m  File "D:\Desktop\HQ_Bot-master\answer_bot.py", line 282, in <module>
    load_json()
[0m[0m[0m[0m[0m[0m  File "D:\Desktop\HQ_Bot-master\answer_bot.py", line 64, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
[0m[0m[0m[0m[0m[0m  File "C:\Users\-\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
[0m[0m[0m[0m[0m[0mUnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 93: character maps to <undefined>
[0m[0m[0m[0m[0m[0m
```
Errors in loading JSON files but dont want to tamper with what you've made

**Comment by 0bytedna** [comment]
Stop posting duplicate thread. Is it that hard to go through the existing issues? Refer the charmap error thread.
