### ISSUE TITLE
FilenotFound error

### ISSUE THREAD

**Issue by itsVikashDubey** [sushant10/HQ_Bot#50]
Traceback (most recent call last):
  File "answer_bot.py", line 286, in <module>
/     Reading screenget_points_live()
  File "answer_bot.py", line 264, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 118, in parse_question
    text = read_screen()
  File "answer_bot.py", line 100, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\vikash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\vikash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\vikash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\vikash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\vikash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

plzzz help

**Comment by itsVikashDubey** [comment]
c'mon reply

**Comment by itsVikashDubey** [comment]
I've tried everything, nothing worked....need your help

**Comment by itsVikashDubey** [comment]
yeah, otherwise it would have been like "**cannot open file named answer.py**"

**Comment by itsVikashDubey** [comment]
![2018-03-26_23h19_33](https://user-images.githubusercontent.com/34867616/37923203-30a74d5a-314c-11e8-987d-fcc78d25102b.png)

**Comment by mnvtrvd** [comment]
Change requirements.txt "Google-Search-API" to "git+https://github.com/abenassi/Google-Search-API/"

**Comment by niiceguy12** [comment]
Same issue. Anybody figure this out?

**Comment by shreyas24cool** [comment]
Same issue here
