### ISSUE TITLE
How Do I install and use this?

### ISSUE THREAD

**Issue by johnnyo1012** [sushant10/HQ_Bot#68]
I installed Python but how do I use the other commands in the read me?

**Comment by Kablamoo123** [comment]
What operating system are you using?

**Comment by johnnyo1012** [comment]
Windows 7

**Comment by Kablamoo123** [comment]
You have to use the command prompt not Python. You can open cmd and then change the directory by typing the command: cd (Then the file location of the folder). It looks like this: 
![cmd](https://user-images.githubusercontent.com/37598308/38423167-021520c8-39a5-11e8-9dac-3379061def7f.PNG)

**Comment by johnnyo1012** [comment]
I did that and now it says pip3 is not recognized as an internal or external command...

**Comment by srivee11** [comment]
Hey could you explain step by step in detail how to install and run the whole thing?
I don't have any knowledge regarding python and packages

**Comment by johnnyo1012** [comment]
@Srivee11 If I can get it to work I will provide you directions.

**Comment by Kablamoo123** [comment]
@johnnyo1012 try just using pip instead of pip3

**Comment by srivee11** [comment]
@johnnyo1012 Alright.Thanks

**Comment by Kablamoo123** [comment]
@srivee11
Just to say, for me the bot isn't fully working and don't use this with a live game as it is against the HQ-Trivia policy.
Step1: Go to the Python website and download Python 3.6.5 : https://www.python.org/downloads/

Step2: Install the code by clicking "Clone or download" and click "Download ZIP": 
![clone](https://user-images.githubusercontent.com/37598308/38424448-04bb51c2-39a9-11e8-93a8-72b78b3da150.PNG)

Step3: Do the above steps that i told @johnnyo1012 to do.

Now I can go with the both of you 😃

**Comment by johnnyo1012** [comment]
I got pip3 install -r requirements.txt to work. 

Now python3 answer_bot.py does not work. Py does also not work...

**Comment by Kablamoo123** [comment]
@johnnyo1012 Have you installed Tesseract and Opencv?

**Comment by johnnyo1012** [comment]
No but when I do brew install tesseract, it says brew is not recognized.

**Comment by johnnyo1012** [comment]
![issue](https://user-images.githubusercontent.com/11791504/38424965-a1a99fa8-3980-11e8-8b00-91230967a95a.JPG)

**Comment by srivee11** [comment]
I've installed python and changed the directory in command.Now what should I do?

**Comment by johnnyo1012** [comment]
Run this- pip3 install -r requirements.txt

**Comment by srivee11** [comment]
I got this

![cap1](https://user-images.githubusercontent.com/29015191/38425714-41a1a5ea-39d2-11e8-9f6f-9debb20316c1.PNG)

**Comment by Kablamoo123** [comment]
@srivee11 Type in what the yellow text says and upgrade  the pip version

**Comment by johnnyo1012** [comment]
I got the same error. Do what the yellow text says and to fix the git I installed this and it fixed it. 

https://git-scm.com/download/win

**Comment by johnnyo1012** [comment]
I got tesseract working but the "brew" command still doesn't work. How do I fix that?

**Comment by Kablamoo123** [comment]
@johnnyo1012  Give me a sec i'm writing a process i had to go through to get it working.

**Comment by johnnyo1012** [comment]
@Kablamoo123 You got it working?

**Comment by Kablamoo123** [comment]
@johnnyo1012  yeah i got this part working but not the whole bot, i'm still waiting for help from someone else.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Great, maybe once you send me the directions to get mine working maybe we can figure out the next issue.

**Comment by srivee11** [comment]
@johnnyo1012 @Kablamoo123 Guys. I installed the new pip version. Now what?

**Comment by Kablamoo123** [comment]
@srivee11 now you need to do the steps that i just explained to @johnnyo1012

**Comment by johnnyo1012** [comment]
@srivee11 

Download this- https://git-scm.com/download/win

**Comment by srivee11** [comment]
@johnnyo1012  Done

**Comment by johnnyo1012** [comment]
@srivee11 Run this command- 

 pip3 install -r requirements.txt

**Comment by johnnyo1012** [comment]
@Kablamoo123 What doesn't work for yours?

**Comment by Kablamoo123** [comment]
@johnnyo1012  im far ahead, my problem is an ssl error: 
![ssl](https://user-images.githubusercontent.com/37598308/38426798-815fab50-39af-11e8-86f7-79ab6939d6c0.PNG)

**Comment by johnnyo1012** [comment]
@Kablamoo123  Maybe I will be able to replicate the error...  

How do I install tesseract from your link?

**Comment by Kablamoo123** [comment]
@johnnyo1012  There should be an executable file.

**Comment by johnnyo1012** [comment]
@Kablamoo123  I downloaded the files and opened the folder and I see shells scripts but no .exe file

**Comment by srivee11** [comment]
@johnnyo1012  I've installed git from the link but I'm getting this error
![cap2](https://user-images.githubusercontent.com/29015191/38427395-c1482be4-39d6-11e8-9f5b-d34da2035070.PNG)

**Comment by johnnyo1012** [comment]
@srivee11 Restart cmd and run as administrator.

**Comment by Kablamoo123** [comment]
@johnnyo1012  Ah i see what i did wrong, you actually weren't meant to install that. I installed an .exe but i'm not sure where from though

**Comment by johnnyo1012** [comment]
@Kablamoo123  I have installed an .exe from this link- https://github.com/UB-Mannheim/tesseract/wiki

It works for another bot and it  is in my path but brew doesn't work...

**Comment by johnnyo1012** [comment]
@Kablamoo123  I tried this bot- https://github.com/maxenxe/HQ-Trivia-Bot

It works but it doesn't read correctly. I don't know a program to set the coordinates.

**Comment by Kablamoo123** [comment]
@johnnyo1012 Ok you have to type in "pip3 install tesseract" or "pip install tesseract" cant remember which one.

**Comment by Kablamoo123** [comment]
@johnnyo1012  ah that bot, i tried that one but for some reason i couldn't wrap my head around it.

**Comment by johnnyo1012** [comment]
@Kablamoo123  pip3 install tesseract worked.

**Comment by johnnyo1012** [comment]
@Kablamoo123 So now tesseract is install so now I need opencv right?

**Comment by johnnyo1012** [comment]
If I do pip3 or pip install opencv it says Could not find a version that satisfies the requirement opencv   

No matching distribution found for opencv

**Comment by Kablamoo123** [comment]
@johnnyo1012 For opencv you type "pip3 install opencv-python" to install it

**Comment by johnnyo1012** [comment]
@Kablamoo123 When I try to run python3 answer_bot.py it says Python3 is not an internal or external command. Do I need to add Python to my Path? I already did so don't know why it doesn't work....

**Comment by Kablamoo123** [comment]
@johnnyo1012 What operating system do you have on your phone?

**Comment by Kablamoo123** [comment]
@johnnyo1012 Yeah you do need to add it to Path. Can you take a screenshot and show me what you added to Path?

**Comment by johnnyo1012** [comment]
@Kablamoo123  I got an iphone x. Python installed in C:\Users\John\AppData\Local\Programs\Python

So I added that to my path.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I added it to PATH under system variables.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I got the python command working.  
python3 answer_bot.py does not work. 

python answer_bot.py works but then I get the issue below....

![issue2](https://user-images.githubusercontent.com/11791504/38431061-0bd57b12-3991-11e8-8a18-7a22a67f9c13.JPG)

**Comment by johnnyo1012** [comment]
@Kablamoo123  Do you know how to fix the above error?

**Comment by Kablamoo123** [comment]
@johnnyo1012  Ah ok this was the first problem i had. You have to open up the code and edit it but not with notepad. I used Wingide-101: http://www.wingware.com/downloads/wingide-101/5.0.3-1/. Then you need to use Wing to open the answer_bot.py and replace line 64 with "sample_questions = json.loads(open("Data/questions.json",encoding="utf8"))

**Comment by johnnyo1012** [comment]
Doing it now, why not notepad++?

**Comment by Kablamoo123** [comment]
Yeah sure you can use that, i'm just more familiar with Wing that's all.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Ok, I did it. I replaced line 64 with exactly this- 

"sample_questions = json.loads(open("Data/questions.json",encoding="utf8"))

**Comment by johnnyo1012** [comment]
@Kablamoo123 Now I get this error..
![anothererror](https://user-images.githubusercontent.com/11791504/38431742-3b6fce3e-3993-11e8-8da8-0db9dec4d79a.JPG)

**Comment by johnnyo1012** [comment]
@Kablamoo123 What do I need to change in the line now? I am not familiar with Python...

**Comment by Kablamoo123** [comment]
@johnnyo1012 You accidentally added the speech marks into the code. Look at it again and edit it.

**Comment by johnnyo1012** [comment]
@Kablamoo123 What speech marks do I remove?

 sample_questions = json.loads(open(Data/questions.json,encoding=utf8))

**Comment by johnnyo1012** [comment]
@Kablamoo123  I also just tried this-

sample_questions = json.loads(open("Data/questions.json",encoding="utf8))

**Comment by srivee11** [comment]
@Kablamoo123 Is everything working for you?

**Comment by johnnyo1012** [comment]
I changed it and now I get this. 
![capture](https://user-images.githubusercontent.com/11791504/38433022-693fa236-3997-11e8-939e-5642d78b05af.JPG)

**Comment by johnnyo1012** [comment]
@srivee11 Kablamoo123 gets another kind of error he does not know how to fix. We are trying to get mine to work to see if I can replicate the error.

**Comment by Kablamoo123** [comment]
@srivee11 Not the whole bot. What part are you up to?

**Comment by Kablamoo123** [comment]
@johnnyo1012  on the same line of code use this : json.load instead of json.loads

**Comment by johnnyo1012** [comment]
@Kablamoo123 That worked. Now it says to press s or q or sampq to do sample questions. I did sample and it seems to work. 

Do you get to the part where you can put s or q?

**Comment by Kablamoo123** [comment]
@johnnyo1012 wait sampq works for you?

**Comment by johnnyo1012** [comment]
@Kablamoo123 This bot doesn't see to work correctly either. When I run it against a youtube video it doesn't show answers. The example questions show answers in green. The real test against youtube doesn't show any answers...
![working](https://user-images.githubusercontent.com/11791504/38433879-783f5a6c-399a-11e8-90e2-429d10071946.JPG)

**Comment by Kablamoo123** [comment]
Let me try my bot again @johnnyo1012

**Comment by johnnyo1012** [comment]
@Kablamoo123 Yes sampq works. Here is a pictur
![bot work](https://user-images.githubusercontent.com/11791504/38433935-a188d51a-399a-11e8-9921-938cc04c821c.JPG)
e of it...

**Comment by srivee11** [comment]
I got to the part where you can put s or q?

**Comment by johnnyo1012** [comment]
@srivee11 That's it for the bot. Now try it with s against a youtube video.

**Comment by Kablamoo123** [comment]
@johnnyo1012  The colours don't even show. You have to download a cursor position program to show the co-ordinates.

**Comment by Kablamoo123** [comment]
@johnnyo1012  You can find where to change the co-ordinates in the code somewhere.

**Comment by johnnyo1012** [comment]
@Kablamoo123  Do you know a good cursor position program? I downloaded one but don't think it works right. What do you mean about the colors? The colors don't show for you?

**Comment by Kablamoo123** [comment]
@johnnyo1012  You know how it shows green if it is the answer? Yeah that doesn't show for me. 
You can download the cursor position here: https://download.cnet.com/Cursor-Position/3001-2383_4-75449858.html

**Comment by johnnyo1012** [comment]
@Kablamoo123 Lol, I downloaded that one and that is what I was using. I'll try changing the coordinates. 

I downloaded a bunch of other stuff trying to get other bots to work. 
I downloaded this- https://www.imagemagick.org/script/download.php

Maybe that will fix it for you?

**Comment by Kablamoo123** [comment]
@johnnyo1012 What does it do?

**Comment by srivee11** [comment]
guys what should I do with the cursor software and where should the video be kept?

**Comment by srivee11** [comment]
@johnnyo1012  yes

**Comment by srivee11** [comment]
like how does the program know which part of the screen to grab and check for the question.
In the bot github page it says to place the recorded phone to the left.I placed the youtube video to the left but that didn't seem to work.

**Comment by Kablamoo123** [comment]
@srivee11 You also need to edit the code to find the co-ordinates of where the video is at. You need to download a cursor position program to know the co-ordinates.

**Comment by srivee11** [comment]
@Kablamoo123  I'll try that.Thanks.did you get it to work?

**Comment by Kablamoo123** [comment]
@srivee11 nope still trying to figure out what to do

**Comment by Kablamoo123** [comment]
@srivee11 is it working for you?

**Comment by srivee11** [comment]
nope

**Comment by johnnyo1012** [comment]
@Kablamoo123 did you set th corrdinates yet? If you did, can you send a screenshot of how you put them in? 

Also what did you do to fix the green colors?

**Comment by Hd1440** [comment]
Hey sorry to interrupt but I have been waiting for someone to help me with my issue so basically I have installed all the required packages to run the bot, however when I proceed to actually run it I get this error:

python answer_bot.py
Traceback (most recent call last):
File "answer_bot.py", line 18, in 
from bs4 import BeautifulSoup
ImportError: No module named bs4

I have already looked at the other issue that is open and it said that the solution is to enter pip3 install bs4, and so I did but it says that it is already installed and satisfied:

pip3 install bs4
Requirement already satisfied: bs4 in c:\users\LOL\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: beautifulsoup4 in c:\users\LOL\appdata\local\programs\python\python36-32\lib\site-packages (from bs4)

I do not know where to go from here, any help is appreciated.

**Comment by Kablamoo123** [comment]
@johnnyo1012  nah i havent set the co-ordinates. And for the green im not sure. I didnt use cd HQ_Bot at the start and just used the python program in the main folder not the sub-folder.

**Comment by Kablamoo123** [comment]
@Hd1440 I'm not sure what to do with that error. If i were you i'd look through open and closed threads to see if there are any solutions with your error and if not, open a new thread to try and look for solutions.

**Comment by Kablamoo123** [comment]
The only reason i could help with the issue is because I also had this issue and people helped me.

**Comment by Kablamoo123** [comment]
@Hd1440 Have you tried using just pip not pip3? It may give the same outcome.

**Comment by Kablamoo123** [comment]
@johnnyo1012 I know its weird that also happens to me. I'm not sure what to do.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Have you tried any other bots?

**Comment by Kablamoo123** [comment]
@johnnyo1012 One other one but i gave up cause for some reason i couldn't understand

**Comment by johnnyo1012** [comment]
@Kablamoo123 People are selling them on youtube for $5. One guy told me he would help me install it and everything. In his video it looks like it worked pretty good.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I don't know if you want to buy one though just to learn how it works...

**Comment by Kablamoo123** [comment]
@johnnyo1012 Are you going to buy it?

**Comment by johnnyo1012** [comment]
@Kablamoo123 I don't know... Its $5. I'm trying to find the youtube video now of it. What do you think?

**Comment by Kablamoo123** [comment]
@johnnyo1012  I'm not that interested to buy one. Quite cheap though. Can you link the video?

**Comment by johnnyo1012** [comment]
@Kablamoo123 

Here is the link- https://www.youtube.com/watch?v=yPWj853hOy0&t=67s

**Comment by Kablamoo123** [comment]
@johnnyo1012  If you do buy it, make sure it can run on Windows.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I contacted him on Instagram and he says it does and he helps install and fix any issues...

I don't want to use this on live HQ or any triva game as that ruins the point of them. Just want to see how accurate they can be on recorded games. 

What did you think of it?

**Comment by Kablamoo123** [comment]
@johnnyo1012  I found this video. Its a longer video but I might check it out on recorded games. https://www.youtube.com/watch?v=XDuK8YMxA8w

**Comment by johnnyo1012** [comment]
@Kablamoo123 You have to do one of those survey things. Did you download the files?

**Comment by johnnyo1012** [comment]
@Kablamoo123 It won't let me complete survey. Did you get the files?

**Comment by Kablamoo123** [comment]
@johnnyo1012 I'm trying now. Give me a sec.

**Comment by Kablamoo123** [comment]
@johnnyo1012  Yeah it doesn't work.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Same.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Now what? Any other ideas?

**Comment by Kablamoo123** [comment]
@johnnyo1012  I don't really want to pay for a bot. Lets just keep looking for alternatives. I'll also open a new thread our problem to see if anyone knows how to fix it.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I payed but he didn't send a link,.. Scam I think.

**Comment by Kablamoo123** [comment]
@johnnyo1012  That sucks.

**Comment by Kablamoo123** [comment]
@johnnyo1012  I guess that makes sense because of what another person said in the comments to him.

**Comment by johnnyo1012** [comment]
@Kablamoo123 Didnt see that....

**Comment by Kablamoo123** [comment]
@johnnyo1012  Yeah i didn't see it at first either but it says 2 Comments so i looked and sorted it by Newest first and it showed up.

**Comment by johnnyo1012** [comment]
@Kablamoo123 I just did that and saw it...

**Comment by johnnyo1012** [comment]
@Kablamoo123 Yes, Whats your number for it?

**Comment by Kablamoo123** [comment]
@johnnyo1012  My number is #8744

**Comment by johnnyo1012** [comment]
@Kablamoo123 Add me johnnyo1012
#3200

Don't know how to add people, not familiar with it.

**Comment by Kablamoo123** [comment]
@johnnyo1012  I have sent a request.

**Comment by Kablamoo123** [comment]
@johnnyo1012  Ok, I tries the bot again and i got something new. I got answers but The question was still messed up.
![works](https://user-images.githubusercontent.com/37598308/38445220-81d81b2c-39ea-11e8-8fa2-7a8e01f2b106.PNG)

**Comment by johnnyo1012** [comment]
@Kablamoo123 Accepted on discord. Ill restart pc and see if it fixes it.

**Comment by srivee11** [comment]
@Kablamoo123 @johnnyo1012  could you guys help me with this?
![cap6](https://user-images.githubusercontent.com/29015191/38452024-89678c6a-3a58-11e8-859a-c5d69d7e10c8.PNG)

**Comment by Kablamoo123** [comment]
@srivee11 I'm not sure what to do for that error. Sorry.

**Comment by beardoholic** [comment]
guys i have done the following steps : 
cloning of the repository 
installed the requirements 
cd HQ_bot
python3 answer_bot.py 
After the above step i open answer_bot in python but it closes after 2 sec of opening.

**Comment by Kablamoo123** [comment]
@beardoholic  Yeah

**Comment by Kablamoo123** [comment]
@srivee11 Nope it didn't work, the image wasn't being read properly and we couldn't find a fix.

**Comment by Kablamoo123** [comment]
@srivee11 If you have discord add me so we can all talk on working how to fix these: Kablamoo101#8744

**Comment by johnnyo1012** [comment]
@Kablamoo123 @srivee11  Add me and we can make a group chat to figure this out together. 

johnnyo1012
#3200

**Comment by jhonny262** [comment]
hey so i have problem it shows 

Googling and searching Wikipediaget_points_sample()
  File "answer_bot.py", line 255, in get_points_sample
    points, maxo = google_wiki(simq, options,neg)
  File "answer_bot.py", line 221, in google_wiki
    search_wiki = google.search(o, num_pages)
NameError: name 'google' is not defined

when i go in sampq
and i have installed req.txt

**Comment by jhonny262** [comment]
any suggestions?

**Comment by srivee11** [comment]
Prime#7934

**Comment by Kablamoo123** [comment]
@jhonny262 Sorry i have no clue, maybe post a thread asking for help?

**Comment by johnnyo1012** [comment]
Everyone join our discord server for help during the HQ games. 
No bots. Just people helping people. 

https://discord.gg/87uZscw

**Comment by IStayLurkin** [comment]
can you guys help me too? I have discord IStayLurking#0726

**Comment by TiNivla** [comment]
What operating system are u guys running on?

**Comment by IStayLurkin** [comment]
windows 10

**Comment by TiNivla** [comment]
hm well im able to run it, you should be able to as well.  Whats the problem?

**Comment by IStayLurkin** [comment]
I'm having trouble entering all the commands and what not, I'm a total noob when it comes to coding and stuff, could you help me figure everything out

**Comment by IStayLurkin** [comment]
add me on discord IStayLurking#0726

**Comment by TiNivla** [comment]
lets talk on the trivia bot channel

**Comment by IStayLurkin** [comment]
in discord?

**Comment by johnnyo1012** [comment]
@IStayLurkin @TiNivla  join our discord- https://discord.gg/Ax6k6

**Comment by Minaeskandar** [comment]
Hey guys do you mind giving the exact steps installing this bot on Windows??

**Comment by Minaeskandar** [comment]
After all the issues you have figured out

**Comment by yashjain1** [comment]
Press s to screenshot live game, sampq to run against sample questions or q to quit:
[0ms
\ Reading screenTraceback (most recent call last):
  File "answer_bot.py", line 288, in <module>
    get_points_live()
  File "answer_bot.py", line 266, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 119, in parse_question
    text = read_screen()
  File "answer_bot.py", line 100, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    |return run_and_get_output(image, 'txt', lang, config, nice) Reading screen
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by yashjain1** [comment]
please help me how to solve this error

**Comment by lucazzzade** [comment]
I have the same issue

**Comment by lucazzzade** [comment]
any updates on fixes ?

**Comment by nileshmurali** [comment]
Uninstall and reinstall tesseract

**Comment by nileshmurali** [comment]
also check your selenium

**Comment by Alienor59** [comment]
I've reinstalled tesseract and checked selenium but i still have the same issue as yashjain1

**Comment by bionichuman** [comment]
@Alienor59 Join our discord for help. 

https://discord.gg/87uZscw

**Comment by Alienor59** [comment]
Ty I joined the discord, who shall I contact ? :)

**Comment by bionichuman** [comment]
@Alienor59 Just type in the channel. Someone will help. Doesnt matter who.

**Comment by luckymahapatra** [comment]
Guys do you any APK file for HQ trivia.if you guys have send me  in my mail 

luckymahapatra009@gmail.com

**Comment by luckymahapatra** [comment]
If anyone has Brain Baazi hack APK.plz send me on luckymahapatra009@gmail.com

**Comment by asti3n97** [comment]
Before installing sushant10/HQ_Bot first download the following programs:
1) python from https://www.python.org/downloads/ download the latest version
2) From the installation processs select add to PATH then continue
3) Install Git from this websites: https://git-scm.com/download/win
4) Install notepad++

Open CMD in admistration
 the first command line will be cd and command line for your path where you download the HQ bot master zip
example: "cd C:\Users\John\Desktop\HQ_Bot-master"
2) second line in command will be "pip install -r requirements.txt" without the quotation mark
3) Third line in command will be "pip install tesseract" without the quotation mark
4) once finish open notepad++ and then select the "answer_bot.py" file to modified it 
5) in notepad++ find "sample_questions = json.loads(open("Data/questions.json").read())" and replace it by "sample_questions = json.loads(open("Data/questions.json", encoding="utf8").read())"
6) Click save once the file is save and modified go back to CMD  and type in "python answer_bot.py"
7) For android download Vysor and for IOS download quicktime player
8)Place the mirror phone to the left and CMD to the right

Note:

Must have high internet speed otherwise the download will failed in CMD
If it ask you to update certain stuffs just followed the commands giving to you.

**Comment by luckymahapatra** [comment]
Thank you.but sir do you have any mobile app for HQand BRAIN BAAZI. please
send the mobile version.
And thank you so much.

**Comment by asti3n97** [comment]
No but you can download the apk file online

**Comment by Shepherd345** [comment]
please I am new to hq trivia and I need help with answering questions correctly.  My mail is nakinrimisi@gmail.com. thank you

**Comment by luckymahapatra** [comment]
Sir I was talking about hack.send me that link plz

**Comment by luckymahapatra** [comment]
Sir could you plz tell me which version of brain baazi will work with
TH.plz is there any solution for brain baazi.thank you

**Comment by lellis2k** [comment]
Can anyone help with this error:

<img width="850" alt="screen shot 2018-07-25 at 20 06 14" src="https://user-images.githubusercontent.com/3228976/43221903-4655ed56-9046-11e8-9b18-e64ca6037b3d.png">

**Comment by joshlee247** [comment]
![screen shot 2018-07-26 at 10 16 49 am](https://user-images.githubusercontent.com/41755366/43277675-953bc0c2-90bd-11e8-9c1b-0e366bbf5ce3.png)

I get this error running "sampq" as well as a similar one running "s". Can anyone help resolve this please.

**Comment by DHANISH-25** [comment]
> Before installing sushant10/HQ_Bot first download the following programs:
> 
> 1. python from https://www.python.org/downloads/ download the latest version
> 2. From the installation processs select add to PATH then continue
> 3. Install Git from this websites: https://git-scm.com/download/win
> 4. Install notepad++
> 
> Open CMD in admistration
> the first command line will be cd and command line for your path where you download the HQ bot master zip
> example: "cd C:\Users\John\Desktop\HQ_Bot-master"
> 2) second line in command will be "pip install -r requirements.txt" without the quotation mark
> 3) Third line in command will be "pip install tesseract" without the quotation mark
> 4) once finish open notepad++ and then select the "answer_bot.py" file to modified it
> 5) in notepad++ find "sample_questions = json.loads(open("Data/questions.json").read())" and replace it by "sample_questions = json.loads(open("Data/questions.json", encoding="utf8").read())"
> 6) Click save once the file is save and modified go back to CMD and type in "python answer_bot.py"
> 7) For android download Vysor and for IOS download quicktime player
> 8)Place the mirror phone to the left and CMD to the right
> 
> Note:
> 
> Must have high internet speed otherwise the download will failed in CMD
> If it ask you to update certain stuffs just followed the commands giving to you.

thank you bro  but i have new problem in next step when search sampq or s

**Comment by DHANISH-25** [comment]
> ![screen shot 2018-07-26 at 10 16 49 am](https://user-images.githubusercontent.com/41755366/43277675-953bc0c2-90bd-11e8-9c1b-0e366bbf5ce3.png)
> 
> I get this error running "sampq" as well as a similar one running "s". Can anyone help resolve this please.

same error bro

**Comment by DHANISH-25** [comment]
> Can anyone help with this error:
> 
> <img alt="screen shot 2018-07-25 at 20 06 14" width="850" src="https://user-images.githubusercontent.com/3228976/43221903-4655ed56-9046-11e8-9b18-e64ca6037b3d.png">

same problem bro any help please
