### ISSUE TITLE
Won't read questions properly.

### ISSUE THREAD

**Issue by Kablamoo123** [sushant10/HQ_Bot#69]
I have the Bot working but the co-ordinates aren't working for me. I have already changed the co-ordinates. The problem is that the text isn't being read properly:
![works](https://user-images.githubusercontent.com/37598308/38445236-9c7c96b0-39ea-11e8-9c1f-991585ee7d3e.PNG)

**Comment by yashjain1** [comment]
Press s to screenshot live game, sampq to run against sample questions or q to quit:
[0ms
\ Reading screenTraceback (most recent call last):
  File "answer_bot.py", line 288, in <module>
    get_points_live()
  File "answer_bot.py", line 266, in get_points_live
    question,options=parse_question()
  File "answer_bot.py", line 119, in parse_question
    text = read_screen()
  File "answer_bot.py", line 100, in read_screen
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    |return run_and_get_output(image, 'txt', lang, config, nice) Reading screen
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\yash\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by yashjain1** [comment]
getting this error
anyone know how to solve this
