### ISSUE TITLE
When i type python3 answer_bot.py 

### ISSUE THREAD

**Issue by PoonamChohdhary1991** [sushant10/HQ_Bot#9]
$ pip3 install -r requirements.txt
Requirement already satisfied: simplejson in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Google-Search-API in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Pillow in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: opencv-contrib-python in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pytesseract in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: beautifulsoup4 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pyscreenshot in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: lxml in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: wikipedia in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: selenium<3.0.0,>=2.44.0 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: requests in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: unidecode in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: vcrpy in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: future in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: numpy>=1.11.3 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from opencv-contrib-python->-r requirements.txt (line 4))
Requirement already satisfied: EasyProcess in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from pyscreenshot->-r requirements.txt (line 7))
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from requests->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from requests->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from requests->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from requests->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: wrapt in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from vcrpy->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: yarl; python_version in "3.4, 3.5, 3.6" in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from vcrpy->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: PyYAML in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from vcrpy->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: six>=1.5 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from vcrpy->Google-Search-API->-r requirements.txt (line 2))
Requirement already satisfied: multidict>=4.0 in c:\users\gandalf\appdata\local\programs\python\python36-32\lib\site-packages (from yarl; python_version in "3.4, 3.5, 3.6"->vcrpy->Google-Search-API->-r requirements.txt (line 2))

Gandalf@DESKTOP-VB16S55 MINGW64 ~/Desktop/HQ_Bot (master)
$ python3 answer_bot.py
bash: python3: command not found

**Comment by sushant10** [comment]
Do you have python3 installed?

**Comment by PoonamChohdhary1991** [comment]
I have python3.6 installed. Now when i type command this shows....
$ py answer_bot.py
Traceback (most recent call last):
  File "answer_bot.py", line 263, in <module>
    load_json()
  File "answer_bot.py", line 53, in load_json
    sample_questions = json.loads(open("Data/questions.json").read())
  File "C:\Users\Gandalf\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 94: character maps to <undefined>

**Comment by sushant10** [comment]
is the command your typing in terminal 
`python3 answer_bot.py`?

**Comment by deviharisakthi** [comment]
same error here please help

**Comment by PoonamChohdhary1991** [comment]
i have windows pc on which when i type python3 answer_bot.py it shows
$ python3 answer_bot.py
bash: python3: command not found
but when i type py answer_bot.py it shows above result

**Comment by sushant10** [comment]
You need to look at how to run python3 on windows, I am not familiar with python on windows.
